/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Verifies the password against the argon2id hash in the `admins` table
         *     and returns a signed JWT (`sub` = admin id, lifetime
         *     `ADMIN_JWT_TTL_MINUTES`, default 480). Unknown email, wrong password,
         *     and inactive admin all return the same `401 invalid_credentials`.
         *     Rate limited per IP. There is no signup endpoint; admins are created
         *     with the CLI (`python -m app.cli create-admin`).
         */
        post: operations["adminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the admin identified by the bearer token */
        get: operations["getCurrentAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List contracts
         * @description Cursor-paginated, newest first. Optional status filter.
         */
        get: operations["listContracts"];
        put?: never;
        /**
         * Create a contract (upload PDF and add signer)
         * @description Stores the PDF, computes its SHA-256, creates the contract in status
         *     `draft` with one signer, and writes a `contract.created` event. Does
         *     not send anything.
         */
        post: operations["createContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: components["parameters"]["ContractId"];
            };
            cookie?: never;
        };
        /** Get a contract with its signer and audit events */
        get: operations["getContract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contracts/{contract_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: components["parameters"]["ContractId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send (or re-send) the signing link
         * @description Generates a new signing token, invalidates any previous one, sets
         *     `expires_at`, moves the contract to `sent`, and **returns the full
         *     signing link** so the admin can copy and share it manually. When
         *     `send_email` is true (default) the link is also emailed to the signer.
         *
         *     The link is returned once, in this response only. It is never stored
         *     and cannot be retrieved later; re-send to get a new one. The web app
         *     must render it in a copy box, not as a navigable anchor.
         *
         *     Allowed from `draft`, `sent`, `viewed`, and `expired`. From `sent` or
         *     `viewed` this is a re-send and writes `link.resent` instead of
         *     `contract.sent`. Rejected with `409` if the contract's signer data
         *     has been anonymized by the retention job.
         */
        post: operations["sendContractLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contracts/{contract_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: components["parameters"]["ContractId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a contract
         * @description Allowed from `draft`, `sent`, and `viewed`. Invalidates the signing
         *     token and writes `contract.cancelled`. Terminal.
         */
        post: operations["cancelContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contracts/{contract_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: components["parameters"]["ContractId"];
            };
            cookie?: never;
        };
        /**
         * Get a short-lived signed URL for the original or signed PDF
         * @description The API never streams PDF bytes. It returns a pre-signed object storage
         *     URL valid for `DOWNLOAD_URL_TTL_SECONDS` (default 300) and writes a
         *     `pdf.downloaded` event. `variant=signed` is only available once the
         *     contract is `signed`.
         */
        get: operations["getContractDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/sign/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 43-character base64url signing token from the emailed link. Never
                 *     logged. The server compares `sha256(token)` against stored hashes.
                 */
                token: components["parameters"]["SigningToken"];
            };
            cookie?: never;
        };
        /**
         * Load a contract for signing
         * @description Validates the token and returns what the signer needs to review and
         *     sign. Side effects: moves `sent` to `viewed` on first call, writes a
         *     `link.viewed` event on every call, and lazily expires the contract if
         *     `expires_at` has passed.
         *
         *     The response is identical for unknown and rotated tokens (`404`).
         */
        get: operations["getContractByToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/sign/{token}/signature": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 43-character base64url signing token from the emailed link. Never
                 *     logged. The server compares `sha256(token)` against stored hashes.
                 */
                token: components["parameters"]["SigningToken"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit the signature
         * @description Accepts the typed name, drawn signature (PNG data URL), and consent.
         *     Stamps the signature block and certificate page onto the PDF, stores
         *     the result, computes its SHA-256, marks the contract `signed`,
         *     invalidates the token, and triggers notifications.
         *
         *     Single use: a second call with the same token returns `410 link_used`.
         *     The operation is atomic with respect to status: concurrent submissions
         *     result in exactly one `signed` transition.
         */
        post: operations["submitSignature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description See SPEC.md §5 for allowed transitions.
         * @enum {string}
         */
        ContractStatus: "draft" | "sent" | "viewed" | "signed" | "expired" | "cancelled";
        /**
         * @default original
         * @enum {string}
         */
        PdfVariant: "original" | "signed";
        /** @enum {string} */
        EventType: "contract.created" | "contract.sent" | "link.resent" | "link.viewed" | "contract.signed" | "contract.expired" | "contract.cancelled" | "pdf.downloaded" | "notification.sent" | "notification.failed" | "signer.anonymized";
        /** @enum {string} */
        ActorType: "admin" | "signer" | "system";
        /** @enum {string} */
        ErrorCode: "bad_request" | "unauthorized" | "invalid_credentials" | "not_found" | "invalid_state" | "link_expired" | "link_used" | "contract_cancelled" | "payload_too_large" | "unsupported_media_type" | "validation_error" | "rate_limited" | "internal_error";
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description Human-readable, safe to show to the end user. */
                message: string;
                /** @description Machine-readable extras. Never contains tokens or PII beyond what the caller already sent. */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            /** @description JWT. Send as `Authorization: Bearer <token>`. */
            access_token: string;
            /** @constant */
            token_type: "bearer";
            /**
             * @description Seconds until the token expires.
             * @example 28800
             */
            expires_in: number;
            admin: components["schemas"]["AdminUser"];
        };
        AdminUser: {
            /**
             * Format: uuid
             * @description Also the JWT `sub`.
             */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            /** Format: date-time */
            last_login_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CreateContractRequest: {
            /**
             * Format: binary
             * @description The contract PDF. `application/pdf`, max 20 MB.
             */
            file: string;
            /** @example Hotel Aurora — Onboarding Agreement 2026 */
            title: string;
            /**
             * Format: date
             * @description Optional end date of the contract term. Drives `retain_until`
             *     (term end + 7 years). Falls back to the signing date if omitted.
             * @example 2028-12-31
             */
            term_end_date?: string;
            /** @example Maria Petrova */
            signer_name: string;
            /**
             * Format: email
             * @example maria@hotelaurora.example
             */
            signer_email: string;
        };
        SendContractRequest: {
            /**
             * @description Email the link to the signer. Set false to share the returned
             *     link manually; the audit event then records `delivery: manual`.
             * @default true
             */
            send_email: boolean;
            /** @description Link lifetime. Defaults to `SIGNING_LINK_TTL_DAYS` (14). */
            expires_in_days?: number;
            /** @description Optional personal note included in the email to the signer. Ignored when `send_email` is false. */
            message?: string;
        };
        CancelContractRequest: {
            /** @description Stored in the `contract.cancelled` event metadata. */
            reason?: string;
        };
        Signer: {
            /** Format: uuid */
            id: string;
            /** @description Null after the retention job anonymizes an unsigned contract. */
            name: string | null;
            /**
             * Format: email
             * @description Null after anonymization.
             */
            email: string | null;
            /** @description True when a non-invalidated, non-expired token exists. */
            has_active_link: boolean;
            /** Format: date-time */
            token_created_at?: string | null;
            /** @description Name typed at signing. Null until signed. */
            typed_name?: string | null;
            /** Format: date-time */
            consent_given_at?: string | null;
            /** @description Version of the consent wording the signer accepted, e.g. `v0-draft`. */
            consent_text_version?: string | null;
            /** @description IPv4 or IPv6 address of the signer at signing. */
            signed_ip?: string | null;
            signed_user_agent?: string | null;
        };
        ContractSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            status: components["schemas"]["ContractStatus"];
            /**
             * Format: uuid
             * @description Id of the admin who created the contract.
             */
            created_by: string;
            /** Format: date */
            term_end_date?: string | null;
            /** @description Null after anonymization. */
            signer_name: string | null;
            /**
             * Format: email
             * @description Null after anonymization.
             */
            signer_email: string | null;
            original_pdf_sha256: string;
            /** @description Null until signed. */
            final_pdf_sha256?: string | null;
            /** Format: date-time */
            sent_at?: string | null;
            /** Format: date-time */
            first_viewed_at?: string | null;
            /** Format: date-time */
            signed_at?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            cancelled_at?: string | null;
            /**
             * Format: date
             * @description Set at signing to (term_end_date or signing date) + 7 years. Informational in v1; nothing is auto-deleted.
             */
            retain_until?: string | null;
            /**
             * Format: date-time
             * @description Set when the retention job removed signer personal data from an unsigned contract.
             */
            anonymized_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ContractEvent: {
            /**
             * Format: int64
             * @description Monotonic per database; orders events within a contract.
             */
            id: number;
            /** Format: uuid */
            contract_id: string;
            event_type: components["schemas"]["EventType"];
            actor_type: components["schemas"]["ActorType"];
            /** @description Admin id or signer id. Null for system events. */
            actor_id?: string | null;
            /** Format: date-time */
            occurred_at: string;
            /** @description Null for system events and after anonymization. */
            ip?: string | null;
            /** @description Null for system events and after anonymization. */
            user_agent?: string | null;
            /** @description Event-specific payload, e.g. `from_status` / `to_status`, `delivery` (email or manual). Never contains the raw token or personal data. */
            metadata: {
                [key: string]: unknown;
            };
        };
        ContractDetail: components["schemas"]["ContractSummary"] & {
            /** @description Bytes. */
            original_pdf_size: number;
            signer: components["schemas"]["Signer"];
            /** @description Full audit log, ascending by `id`. */
            events: components["schemas"]["ContractEvent"][];
        };
        ContractList: {
            items: components["schemas"]["ContractSummary"][];
            /** @description Pass as `cursor` to fetch the next page. Null on the last page. */
            next_cursor: string | null;
        };
        SigningLink: {
            /**
             * Format: uri
             * @description Full signing URL (`{WEB_BASE_URL}/sign/{token}`). Shown to the admin
             *     once. Never stored or logged by the server; must not be logged or
             *     sent to analytics by the client.
             * @example https://contracts.foodverse.example/sign/9Xk2m_VbT4qLw8ZpR1nYc3sDf6hJg0aEu5iOo7tQyWv
             */
            url: string;
            /** Format: date-time */
            expires_at: string;
        };
        SendContractResponse: {
            contract: components["schemas"]["ContractDetail"];
            signing_link: components["schemas"]["SigningLink"];
            /** @description True when `send_email` was true and the SMTP handoff succeeded. False when disabled or when sending failed (see `notification.failed` event). */
            email_sent: boolean;
        };
        DownloadLink: {
            variant: components["schemas"]["PdfVariant"];
            /**
             * Format: uri
             * @description Pre-signed object storage URL. Do not store or log.
             */
            url: string;
            /** Format: date-time */
            expires_at: string;
            /** @description Hash of the file the URL points at, so the caller can verify. */
            sha256: string;
            /** @example hotel-aurora-onboarding-2026-signed.pdf */
            filename: string;
        };
        PublicContract: {
            /** Format: uuid */
            contract_id: string;
            title: string;
            /** @description Always `viewed` in a 200 response (the GET itself moves `sent` to `viewed`). */
            status: components["schemas"]["ContractStatus"];
            signer: {
                /** @description Prefilled into the typed-name field; the signer may edit it. */
                name: string;
                /** Format: email */
                email: string;
            };
            /** @description Display name of the sending organisation, e.g. "Foodverse". Never the admin's personal identity. */
            sent_by?: string;
            /** Format: date-time */
            expires_at: string;
            pdf: {
                /**
                 * Format: uri
                 * @description Short-lived pre-signed URL to the original PDF.
                 */
                url: string;
                /** Format: date-time */
                expires_at: string;
                sha256: string;
                /** @description Bytes. */
                size: number;
            };
            /** @description Exact consent wording the UI must show next to the checkbox. Server-defined so legal wording is versioned in one place. Currently `v0-draft`, pending legal review. */
            consent_text: string;
            /**
             * @description Version identifier of `consent_text`, e.g. `v0-draft`. Echo it back in `SubmitSignatureRequest`.
             * @example v0-draft
             */
            consent_text_version: string;
        };
        SubmitSignatureRequest: {
            /** @description Full legal name as typed by the signer. */
            typed_name: string;
            /**
             * @description Drawn signature as a PNG data URL (`data:image/png;base64,...`).
             *     Max 500 KB decoded, max 2000×1000 px, must decode as PNG.
             */
            signature_image: string;
            /**
             * @description Must be `true`. The UI shows `consent_text` from the GET response.
             * @constant
             */
            consent: true;
            /** @description Echo of `PublicContract.consent_text_version`. Stored on the signer and printed on the certificate page. */
            consent_text_version: string;
        };
        SignatureResult: {
            /** Format: uuid */
            contract_id: string;
            /** @description Always `signed`. */
            status: components["schemas"]["ContractStatus"];
            /** Format: date-time */
            signed_at: string;
            final_pdf_sha256: string;
            /** @description Short-lived link to the signed PDF for immediate download. A copy is also emailed. */
            download: components["schemas"]["DownloadLink"];
        };
    };
    responses: {
        /** @description Malformed request (bad JSON, missing multipart part, bad query value). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "bad_request",
                 *         "message": "Request body is not valid JSON."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "unauthorized",
                 *         "message": "A valid bearer token is required."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Wrong email or password, or inactive admin. Always the same body. */
        InvalidCredentials: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "invalid_credentials",
                 *         "message": "Email or password is incorrect."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Resource not found. For public endpoints this also covers unknown,
         *     malformed, and rotated tokens, deliberately without distinction.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "not_found",
                 *         "message": "Not found."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The contract's current status does not allow this action. */
        InvalidState: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "invalid_state",
                 *         "message": "Contract cannot be cancelled from status 'signed'.",
                 *         "details": {
                 *           "status": "signed",
                 *           "allowed_from": [
                 *             "draft",
                 *             "sent",
                 *             "viewed"
                 *           ]
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The token was valid once but can no longer be used. `details.reason`
         *     tells the web app which message to show.
         */
        LinkGone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Upload or signature image exceeds the size limit. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "payload_too_large",
                 *         "message": "PDF must be 20 MB or smaller.",
                 *         "details": {
                 *           "max_bytes": 20971520
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Uploaded file is not a PDF (checked by content type and magic bytes). */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "unsupported_media_type",
                 *         "message": "Only PDF files are accepted."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request was well-formed but failed field validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "validation_error",
                 *         "message": "One or more fields are invalid.",
                 *         "details": {
                 *           "fields": [
                 *             {
                 *               "field": "signer_email",
                 *               "message": "Not a valid email address."
                 *             },
                 *             {
                 *               "field": "consent",
                 *               "message": "Consent must be true."
                 *             }
                 *           ]
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests from this IP or for this token. */
        RateLimited: {
            headers: {
                /** @description Seconds until the client may retry. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "rate_limited",
                 *         "message": "Too many requests. Try again shortly."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. No partial state is persisted. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "internal_error",
                 *         "message": "Something went wrong. Reference id 7f3c1b2e.",
                 *         "details": {
                 *           "request_id": "7f3c1b2e"
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ContractId: string;
        /**
         * @description 43-character base64url signing token from the emailed link. Never
         *     logged. The server compares `sha256(token)` against stored hashes.
         */
        SigningToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["InvalidCredentials"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current admin. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listContracts: {
        parameters: {
            query?: {
                /** @description Return only contracts in these statuses. Repeat the parameter to pass several. */
                status?: components["schemas"]["ContractStatus"][];
                /** @description Case-insensitive substring match on title, signer name, or signer email. */
                q?: string;
                limit?: number;
                /** @description Opaque cursor from a previous response's `next_cursor`. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of contracts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    createContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateContractRequest"];
            };
        };
        responses: {
            /** @description Contract created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    getContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: components["parameters"]["ContractId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    sendContractLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: components["parameters"]["ContractId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SendContractRequest"];
            };
        };
        responses: {
            /** @description Link issued. Returns the link and the updated contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendContractResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Not sendable from the current status, or signer data has been anonymized. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    cancelContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: components["parameters"]["ContractId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelContractRequest"];
            };
        };
        responses: {
            /** @description Contract cancelled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidState"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    getContractDownloadUrl: {
        parameters: {
            query?: {
                variant?: components["schemas"]["PdfVariant"];
            };
            header?: never;
            path: {
                contract_id: components["parameters"]["ContractId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed download URL. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadLink"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Requested `signed` variant but the contract is not signed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "invalid_state",
                     *         "message": "Contract is not signed; no signed PDF exists.",
                     *         "details": {
                     *           "status": "viewed"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    getContractByToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 43-character base64url signing token from the emailed link. Never
                 *     logged. The server compares `sha256(token)` against stored hashes.
                 */
                token: components["parameters"]["SigningToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract is open for signing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicContract"];
                };
            };
            404: components["responses"]["NotFound"];
            410: components["responses"]["LinkGone"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    submitSignature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 43-character base64url signing token from the emailed link. Never
                 *     logged. The server compares `sha256(token)` against stored hashes.
                 */
                token: components["parameters"]["SigningToken"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitSignatureRequest"];
            };
        };
        responses: {
            /** @description Signature accepted and PDF finalised. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignatureResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            410: components["responses"]["LinkGone"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
}
