"""The Signature Certificate page appended after the contract (SPEC.md §8).

The wording is ``v0-draft`` pending legal review (CLAUDE.md rule 15). Changing
any of the fixed text below means bumping ``CERTIFICATE_TEXT_VERSION`` so old
certificates stay distinguishable in the audit trail.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime
from io import BytesIO
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    Flowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.pdf.fonts import LATIN, LATIN_BOLD, paragraph_markup, register_fonts
from app.pdf.timefmt import DEFAULT_DISPLAY_TIMEZONE, format_both

CERTIFICATE_TEXT_VERSION = "v0-draft"

HEADING = "Signature Certificate"
FOOTER = (
    "Generated by Foodverse Contract Signing. The complete audit log for this "
    "contract is retained by Foodverse. [v0-draft — pending legal review]"
)
NOT_RECORDED = "not recorded"

_MARGIN = 18 * mm
_LABEL_WIDTH = 42 * mm


@dataclass(frozen=True, slots=True)
class AuditEvent:
    """One `contract_events` row as the certificate shows it.

    Deliberately carries no PII: the signer's IP and user agent are printed
    once, from ``CertificateDetails``, not per event.
    """

    event_type: str
    actor_type: str
    occurred_at: datetime


@dataclass(frozen=True, slots=True)
class CertificateDetails:
    """Everything the certificate page prints besides the events and hashes."""

    contract_id: str
    title: str
    signer_name: str
    """Name as entered by the admin."""
    signer_email: str
    signed_at: datetime
    consent_text: str
    consent_text_version: str
    link_sent_at: datetime | None = None
    link_expires_at: datetime | None = None
    signer_ip: str | None = None
    signer_user_agent: str | None = None


@dataclass(frozen=True, slots=True)
class DocumentFacts:
    """Facts about the original PDF, computed by the signing function."""

    original_sha256: str
    page_count: int
    size_bytes: int


def _styles() -> dict[str, ParagraphStyle]:
    register_fonts()
    body = ParagraphStyle(
        "body", fontName=LATIN, fontSize=9, leading=12, splitLongWords=1, shaping=1
    )
    return {
        "body": body,
        "label": ParagraphStyle("label", parent=body, fontName=LATIN_BOLD),
        "mono": ParagraphStyle("mono", parent=body, fontName="Courier", fontSize=8, leading=10),
        "small": ParagraphStyle("small", parent=body, fontSize=8, leading=10),
        "title": ParagraphStyle("title", parent=body, fontName=LATIN_BOLD, fontSize=16, leading=20),
        "h2": ParagraphStyle(
            "h2",
            parent=body,
            fontName=LATIN_BOLD,
            fontSize=11,
            leading=14,
            spaceBefore=8,
            spaceAfter=3,
        ),
        "footer": ParagraphStyle(
            "footer", parent=body, fontSize=8, leading=10, textColor=colors.HexColor("#444444")
        ),
    }


def _human_size(size: int) -> str:
    if size < 1024:
        return f"{size:,} bytes"
    kib = size / 1024
    if kib < 1024:
        return f"{size:,} bytes ({kib:,.1f} KB)"
    return f"{size:,} bytes ({kib / 1024:,.1f} MB)"


def _both_lines(value: datetime | None, tz_name: str) -> str:
    if value is None:
        return NOT_RECORDED
    local, utc = format_both(value, tz_name)
    return f"{escape(local)}<br/>{escape(utc)}"


def _facts_table(
    rows: Sequence[tuple[str, str, str]], styles: dict[str, ParagraphStyle], width: float
) -> Table:
    """``rows`` are (label, value-markup, style-name). Values are already escaped."""
    data = [
        [Paragraph(escape(label), styles["label"]), Paragraph(value, styles[style])]
        for label, value, style in rows
    ]
    table = Table(data, colWidths=[_LABEL_WIDTH, width - _LABEL_WIDTH], hAlign="LEFT")
    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#cccccc")),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    return table


def _events_table(
    events: Sequence[AuditEvent], styles: dict[str, ParagraphStyle], width: float, tz_name: str
) -> Flowable:
    if not events:
        return Paragraph(escape(NOT_RECORDED), styles["body"])
    small = styles["small"]
    head = ParagraphStyle("head", parent=small, fontName=LATIN_BOLD)
    header = [Paragraph(escape(h), head) for h in ("#", "Event", "Actor", tz_name, "UTC")]
    data: list[list[Paragraph]] = [header]
    for index, event in enumerate(events, start=1):
        local, utc = format_both(event.occurred_at, tz_name)
        data.append(
            [
                Paragraph(str(index), small),
                Paragraph(paragraph_markup(event.event_type), small),
                Paragraph(paragraph_markup(event.actor_type), small),
                Paragraph(escape(local), small),
                Paragraph(escape(utc), small),
            ]
        )
    fixed = 8 * mm + 32 * mm + 15 * mm
    remaining = width - fixed
    table = Table(
        data,
        colWidths=[8 * mm, 32 * mm, 15 * mm, remaining * 0.6, remaining * 0.4],
        repeatRows=1,
        hAlign="LEFT",
    )
    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eeeeee")),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#bbbbbb")),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ]
        )
    )
    return table


def render_certificate(
    details: CertificateDetails,
    typed_name: str,
    facts: DocumentFacts,
    events: Sequence[AuditEvent],
    tz_name: str = DEFAULT_DISPLAY_TIMEZONE,
    certificate_text_version: str = CERTIFICATE_TEXT_VERSION,
) -> bytes:
    """Render the certificate as a PDF (one A4 page, more if the trail is long)."""
    styles = _styles()
    width = A4[0] - 2 * _MARGIN
    signed_local, signed_utc = format_both(details.signed_at, tz_name)

    story: list[Flowable] = [
        Paragraph(escape(HEADING), styles["title"]),
        Paragraph(f"Contract <b>{escape(details.contract_id)}</b>", styles["body"]),
        Spacer(1, 6),
        Paragraph("Document", styles["h2"]),
        _facts_table(
            [
                ("Title", paragraph_markup(details.title), "body"),
                ("Original PDF SHA-256", escape(facts.original_sha256), "mono"),
                ("Pages", f"{facts.page_count:,}", "body"),
                ("Size", escape(_human_size(facts.size_bytes)), "body"),
            ],
            styles,
            width,
        ),
        Paragraph("Signer", styles["h2"]),
        _facts_table(
            [
                ("Name (as entered by admin)", paragraph_markup(details.signer_name), "body"),
                ("Typed name (as entered by signer)", paragraph_markup(typed_name), "body"),
                ("Email", paragraph_markup(details.signer_email), "body"),
            ],
            styles,
            width,
        ),
        Paragraph("Signing", styles["h2"]),
        _facts_table(
            [
                ("Signed at", f"{escape(signed_local)}<br/>{escape(signed_utc)}", "body"),
                ("Link sent at", _both_lines(details.link_sent_at, tz_name), "body"),
                ("Link expiry", _both_lines(details.link_expires_at, tz_name), "body"),
                ("Signer IP address", escape(details.signer_ip or NOT_RECORDED), "mono"),
                (
                    "Signer user agent",
                    paragraph_markup(details.signer_user_agent or NOT_RECORDED),
                    "small",
                ),
            ],
            styles,
            width,
        ),
        Paragraph(f"Consent text (version {escape(details.consent_text_version)})", styles["h2"]),
        Paragraph(paragraph_markup(details.consent_text), styles["body"]),
        Paragraph("Audit trail", styles["h2"]),
        _events_table(events, styles, width, tz_name),
        Spacer(1, 12),
        KeepTogether(
            [
                Paragraph(escape(FOOTER), styles["footer"]),
                Paragraph(
                    f"Certificate wording version {escape(certificate_text_version)}.",
                    styles["footer"],
                ),
            ]
        ),
    ]

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=_MARGIN,
        rightMargin=_MARGIN,
        topMargin=_MARGIN,
        bottomMargin=_MARGIN,
        title=HEADING,
        author="Foodverse Contract Signing",
        invariant=1,
    )
    doc.build(story)
    return buffer.getvalue()
